<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<PackageId>RomajiConverter.Core</PackageId>
		<Version>1.0.4</Version>
		<Authors>WL</Authors>
		<RepositoryUrl>https://github.com/xyh20180101/RomajiConverter.WinUI</RepositoryUrl>
		<PackageProjectUrl>https://github.com/xyh20180101/RomajiConverter.WinUI</PackageProjectUrl>
		<PackageLicenseExpression>GPL-2.0-or-later</PackageLicenseExpression>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<MeCabUseDefaultDictionary>False</MeCabUseDefaultDictionary>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MeCab.DotNet" Version="1.2.0" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="RomajiConverter.Core.targets" PackagePath="build/RomajiConverter.Core.targets" />
		<None Include="docs\README.md" Pack="true" PackagePath="\" />
		<Content Include="unidic\*" Pack="true" PackagePath="contentFiles\any\any\unidic\" PackageCopyToOutput="true" />
		<Content Include="customizeDict.txt" Pack="true" PackagePath="contentFiles\any\any\" PackageCopyToOutput="true" />
		<Content Include="Variants\kSimplifiedVariant.txt" Pack="true" PackagePath="contentFiles\any\any\Variants\" PackageCopyToOutput="true" />
		<Content Include="Variants\kTraditionalVariant.txt" Pack="true" PackagePath="contentFiles\any\any\Variants\" PackageCopyToOutput="true" />
	</ItemGroup>
</Project>