<Project>
	<ItemGroup>
		<Files Include="$(MSBuildThisFileDirectory)\..\contentFiles\any\any\unidic\*"/>
		<Files Include="$(MSBuildThisFileDirectory)\..\contentFiles\any\any\customizeDict.txt"/>
		<Files Include="$(MSBuildThisFileDirectory)\..\contentFiles\any\any\Variants\*"/>
	</ItemGroup>
	<Target Name="CopyFiles" BeforeTargets="Build">
		<Copy SourceFiles="@(Files)" DestinationFolder="$(TargetDir)%(RecursiveDir)" />
	</Target>
</Project>